base:
  random_state: 42

data:
  dataset_csv: 'data/raw/iris.csv'
  trainset_path: 'data/processed/train_iris.csv'
  testset_path: 'data/processed/test_iris.csv'

data_split:
  test_size: 0.2

train:
  clf_params:
    C: 0.001
    max_iter: 100
    solver: 'lbfgs'
    multi_class: 'multinomial'
  model_path: models/model.joblib

reports:

